### ISSUE TITLE
[Default Set Bug] Dancer ST

### ISSUE THREAD

**Issue by azy2** [Hildaware/Hilda#6]
The default dancer ST set does not include technical step or devilment

**Comment by jcql** [comment]
Long cooldowns aren't included in the default rotations in order to let the user time them when needed. You should be able to copy the set and add the cooldowns wherever you need them in the rotation (putting them first in the rotation means they will always appear first when usable).

You can also put them in their own set to display outside the default, import string here: 

```
ew0KICAiSWQiOiAiY2UxZDgwZTMtZjdlZS00ZTFlLThkODEtOWI0MDMwMjM3NjYwIiwNCiAgIkpvYklkIjogMzgsDQogICJOYW1lIjogIlRpbnkgRm91bnRhaW4iLA0KICAiRGlzYWJsZWQiOiBmYWxzZSwNCiAgIkFwcFZlcnNpb24iOiAiMC4wLjE3LjAiLA0KICAiVmVyc2lvbiI6ICIxLjAuMCIsDQogICJMYXN0VXBkYXRlZCI6ICIyMDIzLTA4LTI1IDE4OjA2OjMzWiIsDQogICJQcmlvcml0aWVzIjogWw0KICAgIHsNCiAgICAgICJOYW1lIjogIkRldmlsbWVudCIsDQogICAgICAiQWN0aW9uSWQiOiAxNjAxMSwNCiAgICAgICJJZCI6ICI0NzQwMmM4OC0xYjNkLTRjNmItOTUxMy0xY2Q3YTY2ZmZlYTIiLA0KICAgICAgIkNvbmRpdGlvbnMiOiB7fQ0KICAgIH0sDQogICAgew0KICAgICAgIk5hbWUiOiAiVGVjaG5pY2FsIFN0ZXAiLA0KICAgICAgIkFjdGlvbklkIjogMTU5OTgsDQogICAgICAiSWQiOiAiMWI4N2MyMDUtZGIxMy00ZTAzLTg0YWQtYWU2Y2RiYzY5NDZiIiwNCiAgICAgICJDb25kaXRpb25zIjoge30NCiAgICB9DQogIF0NCn0=
```

You'll also want to increase the "weave limit" in the config to show more GCD actions for this to display properly.
